server:
  port: 8081

spring:
  application:
    name: user-service
  grpc:
    server:
      port: 9091
  datasource:
    url: jdbc:postgresql://localhost:5433/microservice_db
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  # RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: user-service

# JWT Configuration
jwt:
  secret: Y2hhbmdlLXRoaXMtdG8tYS1sb25nLXNlY3VyZS1rZXktaW4tcHJvZHVjdGlvbi1lbnZpcm9ubWVudC1hdC1sZWFzdC0yNTYtYml0cw==
  access-token-expiration: 86400000      # 24 giờ (milliseconds)
  refresh-token-expiration: 604800000   # 7 ngày (milliseconds)
